### ISSUE TITLE
Power-ups

### ISSUE THREAD

**Issue by abdallah-altay** [abdallah-altay/GameJam-game-development#18]
Add power-ups that the player can pick up and gain certain effects e.g. freeze NPCs, increase player's movement speed and make player invisible.

**Comment by SB-Lamia** [comment]
I think spliting the powers would be nice and adding a blind guards where it disables the vertical view and keeps the close circle detection of the guard. Is there two you want to do @abdallah-altay ?

**Comment by abdallah-altay** [comment]
I'll work on the freeze and movement speed ones.

**Comment by SB-Lamia** [comment]
sweet Ill do the blind guards and invisible player

**Comment by SB-Lamia** [comment]
Added in #25 and #22 but not yet completed

**Comment by abdallah-altay** [comment]
Completed in #34
